#!/usr/bin/ruby
# encoding: utf-8
# (c) 2011 Martin Kozák (martinkozak@martinkozak.net)

$:.push("./lib")
require "hash-utils"
require "riot"


context "File#touch" do
    setup { File.touch("./~test") }
    asserts(nil) { File.exists? "./~test" }
    teardown { File.unlink("./~test") }
end

context "File#write" do
    setup { File.write("./~test", "some string") }
    asserts(nil) { File.read("./~test") == "some string" }
    teardown { File.unlink("./~test") }
end
